# Generated by Django 2.0.6 on 2018-07-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Incident', 'Incident'), ('Change', 'Change'), ('Mail', 'Mail')], max_length=50)),
                ('updated_by', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('subject', models.TextField(default='Enter the description')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Approved', 'Approved'), ('Blocked', 'Blocked'), ('Pending', 'Pending')], max_length=50)),
            ],
        ),
    ]
