# Generated by Django 2.0.6 on 2018-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180624_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilemodel',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
