# Generated by Django 2.0.6 on 2018-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customprofilemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilemodel',
            name='Phone',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
